### ISSUE TITLE
Post build option Not displayed in jenkins 1.455

### ISSUE THREAD

**Issue by vishalvarshney** [masterthought/jenkins-cucumber-jvm-reports-plugin#1]
I am not able to get this option in jenkins 1.455

**Comment by vishalvarshney** [comment]
When I navigate to installed plugins in jenkin and then to this plugin, i am redirected to git-notes plugin. Can you please rectify this?

**Comment by kingsleyh** [comment]
Hi - you need to also have the ruby-runtime plugin installed to use the ruby version of this plugin. I actually recommend using the java version of this plugin which is here: https://github.com/masterthought/jenkins-cucumber-jvm-reports-plugin-java

The ruby version is still very experimental and it seems jenkins is still not that stable with ruby plugins.

**Comment by kingsleyh** [comment]
I'm only working on the Java version until the ruby plugins become more stable in the future.
